controllers/AddpayController.php
<?php

namespace app\controllers;

use Yii;
use app\models\AddPay;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * AddpayController implements the CRUD actions for AddPay model.
 */
class AddpayController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all AddPay models.
     * @return mixed
     */
    public function actionIndex()
    {
        $model = new AddPay();
        
        $dataProvider = $model->search(Yii::$app->request->get());

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'model' => $model,
        ]);
    }

    /**
     * Displays a single AddPay model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new AddPay model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new AddPay();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing AddPay model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing AddPay model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the AddPay model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return AddPay the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = AddPay::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/BackpayController.php
<?php

namespace app\controllers;

use Yii;
use app\models\BackPay;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * BackpayController implements the CRUD actions for BackPay model.
 */
class BackpayController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all BackPay models.
     * @return mixed
     */
    public function actionIndex()
    {
        $model = new BackPay();
        
        $dataProvider = $model->search(Yii::$app->request->get());

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'model' => $model,
        ]);
    }

    /**
     * Displays a single BackPay model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new BackPay model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new BackPay();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing BackPay model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing BackPay model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the BackPay model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return BackPay the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = BackPay::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/PayController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Pay;
use app\models\AddPay;
use app\models\BackPay;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\ReportMonthForm;
use yii\data\ArrayDataProvider;
use yii\db\Query;

/**
 * PayController implements the CRUD actions for Pay model.
 */
class PayController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Pay models.
     * @return mixed
     */
    public function actionIndex()
    {
        $model = new Pay();
        
        $dataProvider = $model->search(Yii::$app->request->get());

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'model' => $model,
        ]);
    }

    /**
     * Displays a single Pay model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Pay model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Pay();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Pay model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Pay model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Pay model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Pay the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Pay::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionMonthreport(){
        $allModels = [];
        $model = new ReportMonthForm();      
        if ($model->load(Yii::$app->request->post()) && $model->validate()){            
            $month = $model->month+1;
            if ($model->month<10) $model->month = '0'.$model->month;
            if ($month<10) $month = '0'.$month;
            $query = ['and'];
            $query[] = ['>', 'date', $model->year.'-'.$model->month.'-00']; 
            if ($model->month==12){
                $query[] = ['<', 'date', ($model->year+1).'-01-01'];                 
            }else{
                $query[] = ['<', 'date', $model->year.'-'.$month.'-00'];                 
            }                      
            $pays = Pay::find()
                ->where($query)
                ->orderBy('date')
                ->all();                

            $date = '';
            $summa = 0;
            $summa_operator = 0;
            $ostatok = 0;
            if (count($pays)>0) $date = $pays[0]->date;
            foreach ($pays as $pay) {
                if ($pay->date!=$date){
                    $allModels[] = [
                        'date' => $date,
                        'summa' => $summa,
                        'summa_operator' => $summa_operator,
                        'ostatok' => $ostatok,
                    ];
                    $date = $pay->date;                    
                    $summa_operator = $pay->summa;
                    if ($pay->fixed_summa>0)
                        $_summa = $pay->fixed_summa;
                    else
                        $_summa = $this->getGeneralSumma($pay->summa);
                    $ostatok = $_summa;
                    $summa = $_summa+$summa_operator;              
                }else{                    
                    $summa_operator += $pay->summa;
                    if ($pay->fixed_summa>0)
                        $_summa = $pay->fixed_summa;
                    else
                        $_summa = $this->getGeneralSumma($pay->summa);
                    $ostatok += $_summa;
                    $summa += $_summa+$summa_operator;
                }                
            }                            
            if ($date!=''){
                    $allModels[] = [
                        'date' => $date,
                        'summa' => $summa,
                        'summa_operator' => $summa_operator,
                        'ostatok' => $ostatok,
                    ];
                }  

            $pays = AddPay::find()
                ->where($query)
                ->orderBy('date')
                ->all();                
            $date = '';
            $summa = 0;
            $summa_operator = 0;
            $ostatok = 0;
            if (count($pays)>0) $date = $pays[0]->date;
            foreach ($pays as $pay) {
                if ($pay->date!=$date){
                    $allModels[] = [
                        'date' => $date,
                        'summa' => $summa,
                        'summa_operator' => $summa_operator,
                        'ostatok' => $ostatok,
                    ];
                    $date = $pay->date;                    
                    $summa_operator = $pay->summa;
                    if ($pay->use_fixed_summa)
                        $_summa = $pay->fixed_summa;
                    else
                        $_summa = $this->getGeneralSumma($pay->summa);
                    $ostatok = $_summa;
                    $summa = $_summa+$summa_operator;          
                }else{                    
                    $summa_operator += $pay->summa;
                    $_summa = $pay->fixed_summa;                    
                    $ostatok += $_summa;
                    $summa += $_summa+$summa_operator;
                }                
            }            
            if ($date!=''){
                    $allModels[] = [
                        'date' => $date,
                        'summa' => $summa,
                        'summa_operator' => $summa_operator,
                        'ostatok' => $ostatok,
                    ];
                }  

            $pays = BackPay::find()
                ->where($query)
                ->orderBy('date')
                ->all();                
            $date = '';
            $summa = 0;
            $summa_operator = 0;
            $ostatok = 0;
            if (count($pays)>0) $date = $pays[0]->date;
            foreach ($pays as $pay) {
                if ($pay->date!=$date){
                    $allModels[] = [
                        'date' => $date,
                        'summa' => $summa,
                        'summa_operator' => $summa_operator,
                        'ostatok' => $ostatok,
                    ];
                    $date = $pay->date;                    
                    $summa_operator = $pay->summa_operator;                   
                    $summa = $summa_operator;              
                }else{                    
                    $summa_operator += $pay->summa_operator;                    
                    $summa += $summa_operator;
                }                
            }                            
            if ($date!=''){
                    $allModels[] = [
                        'date' => $date,
                        'summa' => $summa,
                        'summa_operator' => $summa_operator,
                        'ostatok' => $ostatok,
                    ];                   
                }  

            usort($allModels, function ($val1, $val2){
                    if ($val1['date']<$val2['date']) return -1;
                    elseif ($val1['date']>$val2['date']) return 1;
                    else return 0;
            });            
            $allModels = $this->dateTogether($allModels);
        }
        $query = new Query();
        $dataProvider = new ArrayDataProvider([
            'allModels' => $allModels,
            // 'sort' => [
            //     'attributes' => ['id', 'username', 'email'],
            // ],
            'pagination' => [
                'pageSize' => 10,
            ],
        ]);
        return $this->render('monthReport', ['model' => $model, 'dataProvider' => $dataProvider]);            
    }

    private function getGeneralSumma($summa){        
        if ($summa>1 && $summa<10000)
            return 200;
        elseif ($summa>=10000 && $summa<20000)
            return 500;
        elseif ($summa>=20000)
            return 500;
        else
            return 0;
    }    

    private function dateTogether($in){
        $out = [];
        for ($i=0; $i < count($in)-1; $i++) { 
            if ($in[$i]['date']==$in[$i+1]['date']){
                $out[] = [

views/pay/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\jui\DatePicker;
use app\models\Country;
use app\models\Operator;

/* @var $this yii\web\View */
/* @var $model app\models\Pay */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="pay-form">

    <?php $form = ActiveForm::begin(); ?>
    <div class="left w45 pr20">
        <?= $form->field($model, 'contract')->textInput(['maxlength' => 255]) ?>

        <?php //$form->field($model, 'date')->textInput() ?>
        <div class="form-group field-pay-date">
            <label class="control-label" for="pay-date">Дата</label><br/>
            <?= DatePicker::widget([
                    'name'  => 'Pay[date]',
                    'value'  => $model->date ? $model->date : time(),
                    'id'=>"pay-date",   
                    'dateFormat' => 'yyyy-MM-dd',                           
                ]); ?>
            <div class="help-block"></div>
        </div>

        <?= $form->field($model, 'operator_id')->dropDownList(Operator::getAllItems()) ?>

        <?= $form->field($model, 'customer')->textInput() ?>

        <?= $form->field($model, 'summa')->textInput() ?>

        <?= $form->field($model, 'count_18')->textInput() ?>
    </div>
    <div class="left w45">
        <?= $form->field($model, 'count_28')->textInput() ?>

        <?= $form->field($model, 'count_other')->textInput() ?>

        <?= $form->field($model, 'country_id')->dropDownList(Country::getAllItems()); ?>

        <?= $form->field($model, 'count_day')->textInput() ?>

        <?= $form->field($model, 'fixed_summa')->textInput() ?>

        <?= $form->field($model, 'use_fixed_summa')->checkBox() ?>
    </div>
    <div class="clear"></div>
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Отправить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/pay/_monthReportForm.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Pay */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="pay-form">

    <?php $form = ActiveForm::begin(); ?>
    <div class="left w25 pr20">
        <?= $form->field($model, 'month')->dropDownList([
            1 => 'Январь',
            2 => 'Февраль',
            3 => 'Март',
            4 => 'Апрель',
            5 => 'Май',
            6 => 'Июнь',
            7 => 'Июль',
            8 => 'Август',
            9 => 'Сентябрь',
            10 => 'Октябрь',
            11 => 'Ноябрь',
            12 => 'Декабрь',
        ]) ?>
    </div>
    <div class="left w25 pr20">
        <?= $form->field($model, 'year')->dropDownList(['2010'=>'2010', '2011'=>'2011', '2012'=>'2012', '2013'=>'2013', '2014'=>'2014', '2015'=>'2015', '2016'=>'2016', '2017'=>'2017', '2018'=>'2018', '2019'=>'2019', '2020'=>'2020']) ?>        
    </div>
    
    <div class="form-group" style="padding-top:25px;">
        <?= Html::submitButton('Отправить', ['class' => 'btn btn-primary']) ?>
    </div>

    <div class="clear"></div>
    <?php ActiveForm::end(); ?>

</div>

views/pay/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Pay */

$this->title = 'Создать новый платеж';
$this->params['breadcrumbs'][] = ['label' => 'Платежи', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pay-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/pay/detailReport.php
<?php
	use yii\grid\GridView;

    $this->title = 'Детальный отчет';
    $this->params['breadcrumbs'][] = ['label' => 'Платежи', 'url' => ['index']];
    $this->params['breadcrumbs'][] = $this->title;
?>

<?= $this->render('_monthReportForm', ['model' => $model]); ?>
	<hr/>
<?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],         
            'contract',
            'date',
            'customer',
            'operator',
            'summa',
            'summa_operator',
            'ostatok',
            'type',
            // 'count_other',
            // 'count_day',

            // ['class' => 'yii\grid\ActionColumn'],
        ],
    ]);	
?>

views/pay/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Платежы';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pay-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Создать платеж', ['create'], ['class' => 'btn btn-success']) ?>
        <?= Html::a('Создать доп платеж', ['/addpay/create'], ['class' => 'btn btn-success']) ?>
        <?= Html::a('Создать возврат', ['/backpay/create'], ['class' => 'btn btn-success']) ?>
    </p>
    <p>
    <?= Html::a('Отчет за месяц', ['monthreport'], ['class' => 'btn btn-primary']) ?>
    <?= Html::a('Детальный отчет', ['detailreport'], ['class' => 'btn btn-primary']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $model,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'contract',
            'date',
            'operator.title',
            'customer',
            'summa',
            // 'count_18',
            // 'count_28',
            // 'count_other',
            'country.title',
            'count_day',
            // 'fixed_summa',

            [
                'class' => 'yii\grid\ActionColumn',
                'headerOptions' => ['width'=>'7%'],
            ],
        ],
    ]); ?>

</div>

views/pay/monthReport.php
<?php
	use yii\grid\GridView;

    $this->title = 'Отчет за месяц';
    $this->params['breadcrumbs'][] = ['label' => 'Платежи', 'url' => ['index']];
    $this->params['breadcrumbs'][] = $this->title;
?>

<?= $this->render('_monthReportForm', ['model' => $model]); ?>
	<hr/>
<?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],                  
            'date',
            'summa',
            'summa_operator',
            'ostatok',
            // 'count_other',
            // 'count_day',

            // ['class' => 'yii\grid\ActionColumn'],
        ],
    ]);	
?>

views/pay/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Pay */

$this->title = 'Редактировать платеж: ' . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Платежы', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Редактировать';
?>
<div class="pay-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/pay/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Pay */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Платежи', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pay-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Редактировать', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вы уверены что хотите удалить платеж?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'contract',
            'date',
            'operator_id',
            'customer',
            'summa',
            'count_18',
            'count_28',
            'count_other',
            'country_id',
            'count_day',
            'fixed_summa',
        ],
    ]) ?>

</div>